
spring:
  application.name: products

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/productdb
    driverClassName: org.h2.Driver
    username: sa
    password: louis
  h2:
    console:
      enabled: true

server:
  port: 8081

